import Head from "next/head"
import Image from "next/image"
import styles from "../../styles/pasarelap.module.css"
import data from "public/utils/data"
import Checkout from '../../../components/pasarelaPago/Checkout'

export default function Pagos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pagos StarLnk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
        <h1 className={styles.title}>1 vCPU</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/cloud.png"
              alt="cloud"
              width={150}
              height={150}
              />
            <p>sin atencion permanente</p>
            <button className={styles.button} onClick={(() => {
              Checkout({
                lineItems: [
                  {
                    price: "price_1McDhyBK4uk3P92pmaVM3wJV",
                    quantity: 1
                  }
                ]
              })
            })}>COMPRAR!</button>
          </div>
        </div>
      </div>
      <div className={styles.card}>
        <h1 className={styles.title}>2 vCPU</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/cloud.png"
              alt="cloud"
              width={150}
              height={150}
              />
            <p>atencion per call</p>
            <button className={styles.button} onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1McDlgBK4uk3P92pAsTKKeCP",
                    quantity: 1
                  }
                ]
              })
            })}>COMPRAR!</button>
          </div>
        </div>
        
        </div>
      </main>
    </div>
  )
}
